# Libraries

In [1]:
!nvidia-smi

Wed May 11 13:33:47 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
!pip install haven-ai
!pip install kornia
!pip uninstall opencv-python-headless==4.5.5.62 -y
!pip install opencv-python-headless==4.1.2.30
!pip install torchinfo

Found existing installation: opencv-python-headless 4.1.2.30
Uninstalling opencv-python-headless-4.1.2.30:
  Successfully uninstalled opencv-python-headless-4.1.2.30
  Using cached opencv_python_headless-4.1.2.30-cp37-cp37m-manylinux1_x86_64.whl (21.8 MB)


In [4]:
%cd '/content/drive/MyDrive/deepfish/localize_fish/'
#!git clone https://github.com/alzayats/DeepFish.git
#!git clone https://github.com/ElementAI/LCFCN

/content/drive/MyDrive/deepfish/localize_fish


In [5]:
from haven import haven_chk as hc
from haven import haven_results as hr
from haven import haven_utils as hu
import torch
import torchvision
import tqdm
import pandas as pd
import pprint
import itertools
import os
import pylab as plt
import time
import numpy as np

from src import *
import argparse

from torch.utils.data import sampler
from torch.utils.data.sampler import RandomSampler
from torch.backends import cudnn
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torchvision import models
from torchinfo import summary

cudnn.benchmark = True

# Training

In [6]:
!python3 '/content/drive/MyDrive/deepfish/localize_fish/scripts/train_single_image.py' -e seg -d '/content/drive/MyDrive/deepfish/Dataset/DeepFish'

0 {'loss_seg': 0.35444363951683044}
array([[ 438417, 1635183],
       [      0,       0]])
1 {'loss_seg': 0.27516499161720276}
array([[ 825778, 1247822],
       [      0,       0]])
2 {'loss_seg': 0.2311033010482788}
array([[1377662,  695938],
       [      0,       0]])
3 {'loss_seg': 0.18832339346408844}
array([[1812651,  260949],
       [      0,       0]])
4 {'loss_seg': 0.15503793954849243}
array([[1968686,  104914],
       [      0,       0]])
5 {'loss_seg': 0.12906448543071747}
array([[2019835,   53765],
       [      0,       0]])
6 {'loss_seg': 0.10745315998792648}
array([[2046336,   27264],
       [      0,       0]])
7 {'loss_seg': 0.08853590488433838}
array([[2058788,   14812],
       [      0,       0]])
8 {'loss_seg': 0.07269277423620224}
array([[2064665,    8935],
       [      0,       0]])
9 {'loss_seg': 0.06017184257507324}
array([[2064792,    8808],
       [      0,       0]])


In [7]:
#!python3 '/content/drive/MyDrive/deepfish/localize_fish/trainval.py' -e seg -sb '/content/seg_checkpoint/' -d '/content/drive/MyDrive/deepfish/Dataset/DeepFish' -r 1 -nw 2