# Libraries

In [1]:
!nvidia-smi

Tue Jun  7 00:20:24 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P0    32W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!pip install haven-ai
!pip install kornia
!pip uninstall opencv-python-headless==4.5.5.62 -y
!pip install opencv-python-headless==4.1.2.30
!pip install torchinfo
!pip install timm
!pip install einops==0.3.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 92 kB 534 kB/s 
     |████████████████████████████████| 47.8 MB 127 kB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 512 kB 8.6 MB/s 
Found existing installation: opencv-python-headless 4.5.5.64
Uninstalling opencv-python-headless-4.5.5.64:
  Successfully uninstalled opencv-python-headless-4.5.5.64
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 21.8 MB 7.3 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 431 kB 7.9 MB/s 
Looking in indexes: https://pypi.org/simple, https://

In [4]:
# %cd /content/drive/MyDrive/deepfish/affinity_lcfcn
#!git clone https://github.com/IssamLaradji/affinity_lcfcn.git
#!git clone https://github.com/haven-ai/haven-ai.git

# %cd /content/drive/MyDrive/Thao_PythonPaper/DeepFish_supervised/DeepFish_master
%cd /content/drive/MyDrive/deepfish/DeepFish_master

/content/drive/MyDrive/deepfish/DeepFish_master


In [5]:
from haven import haven_chk as hc
from haven import haven_results as hr
from haven import haven_utils as hu
import torch
import torchvision
import tqdm
import pandas as pd
import pprint
import itertools
import os
import pylab as plt
import time
import numpy as np

from src import *
import argparse

from torch.utils.data import sampler
from torch.utils.data.sampler import RandomSampler
from torch.backends import cudnn
from torch.nn import functional as F
from torch.utils.data import DataLoader
from torchvision import models
from torchinfo import summary

cudnn.benchmark = True

# Training

In [6]:
#!python3 '/content/drive/MyDrive/deepfish/affinity_lcfcn/trainval.py' -e weakly_JCUfish -sb '/content/seg_checkpoint/' -d '/content/drive/MyDrive/deepfish/Dataset/DeepFish/' -r 1 -nw 2

In [7]:
#!python3 '/content/drive/MyDrive/deepfish/affinity_lcfcn/trainval.py' -e weakly_JCUfish -sb '/content/seg_checkpoint/' -d '/content/drive/MyDrive/deepfish/Dataset/DeepFish/' -r 1 -nw 2

In [8]:
# !python3 '/content/drive/MyDrive/Thao_PythonPaper/Students_Projects/deepfish/affinity_lcfcn/trainval.py' -e weakly_JCUfish_aff -sb '/content/seg_checkpoint/' -d '/content/drive/MyDrive/Thao_PythonPaper/Students_Projects/deepfish/Dataset/DeepFish/' -r 1 -nw 2

In [9]:
!pip install git+https://github.com/ElementAI/LCFCN

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/ElementAI/LCFCN to /tmp/pip-req-build-vvpqzybr
  Running command git clone -q https://github.com/ElementAI/LCFCN /tmp/pip-req-build-vvpqzybr
  Created wheel for lcfcn: filename=lcfcn-0.6.0-py3-none-any.whl size=11476 sha256=a8434523001f367dc8616e98775b56556ffc4412352cc374430480389afcebaf
  Stored in directory: /tmp/pip-ephem-wheel-cache-9h7v5zv_/wheels/ae/84/c8/33ebd41907f5cdc91f3792e65cf800782f471de7e971371d40
Successfully built lcfcn


In [10]:
# python scripts/train_single_image.py -e seg -d ${PATH_TO_DATASET}

## Train single image: Localization task

In [11]:
#!python3 '/content/drive/MyDrive/deepfish/DeepFish_master/scripts/train_single_image.py' -e loc -d '/content/drive/MyDrive/deepfish/Dataset/DeepFish/'

In [12]:
# python scripts/train_single_image.py -e loc -d ${PATH_TO_DATASET}

## Train single image: Segmentation task

In [1]:
!python3 '/content/drive/MyDrive/deepfish/DeepFish_master/scripts/train_single_image.py' -e seg -d '/content/drive/MyDrive/deepfish/Dataset/DeepFish/'

0 {'loss_seg': 0.18134503066539764}
array([[1932403,  107130],
       [  34067,       0]])
1 {'loss_seg': 0.10337767750024796}
array([[2038227,    1306],
       [  33590,     477]])
2 {'loss_seg': 0.06936512887477875}
array([[2039533,       0],
       [  32084,    1983]])
3 {'loss_seg': 0.051084842532873154}
array([[2039531,       2],
       [  28730,    5337]])
4 {'loss_seg': 0.036765314638614655}
array([[2039411,     122],
       [  24266,    9801]])
5 {'loss_seg': 0.025475839152932167}
array([[2039049,     484],
       [  20650,   13417]])
6 {'loss_seg': 0.017188863828778267}
array([[2038428,    1105],
       [  17879,   16188]])
7 {'loss_seg': 0.01158042624592781}
array([[2037734,    1799],
       [  14555,   19512]])
8 {'loss_seg': 0.007953321561217308}
array([[2037124,    2409],
       [  12131,   21936]])
9 {'loss_seg': 0.005717651452869177}
array([[2036656,    2877],
       [   9531,   24536]])
10 {'loss_seg': 0.004231547471135855}
array([[2036206,    3327],
       [   5217,   

### Save contour evolution:

In [ ]:
#!python3 '/content/drive/MyDrive/deepfish/DeepFish_master/scripts/train_single_image2.py' -e seg -d '/content/drive/MyDrive/deepfish/Dataset/DeepFish/'

#Train and test on the dataset

## Segmentation task:

###FCN8

In [ ]:
# !python3 '/content/drive/MyDrive/deepfish/DeepFish_master/trainval.py' -e seg -sb '/content/drive/MyDrive/deepfish/DeepFish_master/temp_results' -d '/content/drive/MyDrive/deepfish/Dataset/DeepFish/' -r 1

In [ ]:
!python3 '/content/drive/MyDrive/deepfish/DeepFish_master/trainval.py' -e seg -sb '/content/drive/MyDrive/deepfish/DeepFish_master/temp_results' -d '/content/drive/MyDrive/deepfish/Dataset/DeepFish/' -r 1


Running 1 experiments

******
Haven: 0.6.7
Exp id: af76c072bd29235df5cfac79ad9b3aaf

Hyperparameters:
----------------
{'batch_size': 1,
 'dataset': 'fish_seg',
 'max_epoch': 100,
 'model': 'fcn8_wide_resnet',
 'task': 'seg',
 'transform': 'rgb_normalize',
 'wrapper': 'seg_wrapper'}

Save directory: /content/drive/MyDrive/deepfish/DeepFish_master/temp_results/af76c072bd29235df5cfac79ad9b3aaf
Running on device: cuda
Downloading: "https://download.pytorch.org/models/wide_resnet50_2-95faca4d.pth" to /root/.cache/torch/hub/checkpoints/wide_resnet50_2-95faca4d.pth
100% 132M/132M [00:02<00:00, 49.4MB/s]
0 - visualizing val image - savedir:af76c072bd29235df5cfac79ad9b3aaf
1 - visualizing val image - savedir:af76c072bd29235df5cfac79ad9b3aaf
2 - visualizing val image - savedir:af76c072bd29235df5cfac79ad9b3aaf
Validating
100% 124/124 [02:44<00:00,  1.33s/it]
Training
100% 310/310 [08:25<00:00,  1.63s/it]
   epoch  ...  loss_seg
0      0  ...    0.0123

[1 rows x 3 columns]
Saved in /content/dri

###Unet

In [ ]:
# !python3 '/content/drive/MyDrive/deepfish/DeepFish_master/trainval_unet.py' -e seg -sb '/content/drive/MyDrive/deepfish/DeepFish_master/temp_results' -d '/content/drive/MyDrive/deepfish/Dataset/DeepFish/' -r 1